# config for replicated deployment
deployment:
  # config for replicated container
  replicated:
    repository: quay.io/replicated/replicated
    tag: latest
    pullPolicy: IfNotPresent
    env:
      releaseSequence: ""
      proxyAddress: ""
      noProxyAddress: "10.96.0.0/12"
      customerBaseURLOverride: ""
  # config for replicated-ui container
  ui:
    repository: quay.io/replicated/replicated-ui
    tag: latest
    pullPolicy: IfNotPresent
  # shared env configs with replicated and ui
  env:
    releaseChannel: "stable"
    logLevel: "info"

# config for replicated-ui service
uiService:
  type: NodePort
  port: 8800

# storage class name used for pvcs
persistence:
  storageClass: "standard"

# config for clusterrole
clusterRole:
  namespace: "default"
