DATE=$(shell date +%Y%m%d)

v1.9.3:
	docker build --build-arg VERSION=1.9.3 \
		-t replicated/k8s-packages:ubuntu-1604-v1.9.3-${DATE} .
	docker push replicated/k8s-packages:ubuntu-1604-v1.9.3-${DATE}

v1.10.6:
	docker build --build-arg VERSION=1.10.6 \
		-t replicated/k8s-packages:ubuntu-1604-v1.10.6-${DATE} .
	docker push replicated/k8s-packages:ubuntu-1604-v1.10.6-${DATE}

v1.11.5:
	docker build --build-arg VERSION=1.11.5 \
		-t replicated/k8s-packages:ubuntu-1604-v1.11.5-${DATE} .
	docker push replicated/k8s-packages:ubuntu-1604-v1.11.5-${DATE}

v1.12.3:
	docker build --build-arg VERSION=1.12.3 \
		-t replicated/k8s-packages:ubuntu-1604-v1.12.3-${DATE} .
	docker push replicated/k8s-packages:ubuntu-1604-v1.12.3-${DATE}

v1.13.5:
	docker build --build-arg VERSION=1.13.5 \
		-t replicated/k8s-packages:ubuntu-1604-v1.13.5-${DATE} .
	docker push replicated/k8s-packages:ubuntu-1604-v1.13.5-${DATE}

v1.14.3:
	docker build --build-arg VERSION=1.14.3 \
		-t replicated/k8s-packages:ubuntu-1604-v1.14.3-${DATE} .
	docker push replicated/k8s-packages:ubuntu-1604-v1.14.3-${DATE}

v1.15.12:
	docker build --build-arg VERSION=1.15.12 \
		-t replicated/k8s-packages:ubuntu-1604-v1.15.12-${DATE} .
	docker push replicated/k8s-packages:ubuntu-1604-v1.15.12-${DATE}
