---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicated-hostpath-provisioner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: controller
      kind: storage-provisioner
  template:
    metadata:
      labels:
        tier: controller
        kind: storage-provisioner
    spec:
      containers:
      - name: replicated-hostpath-provisioner
        image: quay.io/replicated/replicated-hostpath-provisioner:cd1d272
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PV_BASE_PATH
          value: "$PV_BASE_PATH"
        volumeMounts:
          - name: pv-volume
            mountPath: /opt/replicated/hostpath-provisioner
        # https://github.com/rimusz/charts/blob/b3aef3bf5a3519f0a1a79c0569e8233bdec0e30d/stable/hostpath-provisioner/values.yaml#L35-L41
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
        - name: pv-volume
          hostPath:
            path: "$PV_BASE_PATH"
            type: DirectoryOrCreate
      serviceAccountName: hostpath-provisioner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hostpath-provisioner
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: hostpath-provisioner
subjects:
- kind: ServiceAccount
  name: hostpath-provisioner
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:persistent-volume-provisioner
---
# The default system:persistent-volume-provisioner role in Kubernetes 1.11 is insufficient:
# - crud for events and endpoints
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostpath-provisioner-extra
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - events
  verbs:
  - create
  - patch
  - update
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hostpath-provisioner-extra
subjects:
- kind: ServiceAccount
  name: hostpath-provisioner
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hostpath-provisioner-extra
