---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicated-hostpath-provisioner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: controller
      kind: storage-provisioner
  template:
    metadata:
      labels:
        tier: controller
        kind: storage-provisioner
    spec:
      containers:
      - name: replicated-hostpath-provisioner
        image: quay.io/replicated/replicated-hostpath-provisioner:cd1d272
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PV_BASE_PATH
          value: "$PV_BASE_PATH"
        volumeMounts:
          - name: pv-volume
            mountPath: /opt/replicated/hostpath-provisioner
      volumes:
        - name: pv-volume
          hostPath:
            path: "$PV_BASE_PATH"
            type: DirectoryOrCreate
      serviceAccountName: hostpath-provisioner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hostpath-provisioner
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: hostpath-provisioner
subjects:
- kind: ServiceAccount
  name: hostpath-provisioner
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:persistent-volume-provisioner
---
# The default system:persistent-volume-provisioner role in Kubernetes 1.8 is
# insufficient:
#
# I1007 18:09:10.073558       1 controller.go:874] cannot start watcher for PVC default/testpvc: events is forbidden: User "system:serviceaccount:kube-system:hostpath-provisioner" cannot list events in the namespace "default": access denied
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostpath-provisioner-extra
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - events
  verbs:
  - create
  - patch
  - update
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hostpath-provisioner-extra
subjects:
- kind: ServiceAccount
  name: hostpath-provisioner
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hostpath-provisioner-extra
