version: '2'

services:
  install-scripts:
    build: .
    container_name: "replicated.install-scripts"
    ports:
      - "8090:5000"
    restart: always
    environment:
      ENVIRONMENT: dev
      REPLICATED_INSTALL_URL: http://localhost:8090
      MYSQL_USER: replicated
      MYSQL_PASS: password
      MYSQL_HOST: 172.17.0.1
      MYSQL_PORT: 30306
      MYSQL_DB: replicated
    volumes:
      - .:/usr/src/app
    command: [python, main.py]
