apiVersion: apps/v1
kind: Deployment
metadata:
  name: install-scripts
spec:
  template:
    spec:
      containers:
        - name: install-scripts
          image: replicated-install-scripts
          env:
            - name: MYSQL_PASSWORD
              value: password
              valueFrom: ~
