apiVersion: v1
kind: Service
metadata:
  name: install-scripts-np
  labels:
    app: install-scripts
spec:
  type: NodePort
  ports:
  - name: install-scripts
    port: 5000
    targetPort: install-scripts
    nodePort: 30090
  selector:
    app: install-scripts
