DATE=$(shell date +%Y%m%d)

v1.9.3:
	docker build --pull --build-arg VERSION=1.9.3 \
		-t quay.io/replicated/k8s-packages:rhel7-v1.9.3-${DATE} .
	docker push quay.io/replicated/k8s-packages:rhel7-v1.9.3-${DATE}

v1.10.6:
	docker build --pull --build-arg VERSION=1.10.6 \
		-t quay.io/replicated/k8s-packages:rhel7-v1.10.6-${DATE} .
	docker push quay.io/replicated/k8s-packages:rhel7-v1.10.6-${DATE}

v1.11.5:
	docker build --pull --build-arg VERSION=1.11.5 \
		-t quay.io/replicated/k8s-packages:rhel7-v1.11.5-${DATE} .
	docker push quay.io/replicated/k8s-packages:rhel7-v1.11.5-${DATE}

v1.12.3:
	docker build --pull --build-arg VERSION=1.12.3 \
		-t quay.io/replicated/k8s-packages:rhel7-v1.12.3-${DATE} .
	docker push quay.io/replicated/k8s-packages:rhel7-v1.12.3-${DATE}

v1.13.5:
	docker build --pull --build-arg VERSION=1.13.5 \
		-t quay.io/replicated/k8s-packages:rhel7-v1.13.5-${DATE} .
	docker push quay.io/replicated/k8s-packages:rhel7-v1.13.5-${DATE}

v1.14.3:
	docker build --pull --build-arg VERSION=1.14.3 \
		-t quay.io/replicated/k8s-packages:rhel7-v1.14.3-${DATE} .
	docker push quay.io/replicated/k8s-packages:rhel7-v1.14.3-${DATE}

v1.15.3:
	docker build --pull --build-arg VERSION=1.15.3 \
		-t quay.io/replicated/k8s-packages:rhel7-v1.15.3-${DATE} .
	docker push quay.io/replicated/k8s-packages:rhel7-v1.15.3-${DATE}
