apiVersion: apps/v1
kind: Deployment
metadata:
  name: install-scripts
spec:
  replicas: 3
  template:
    spec:
      nodeSelector:
        replicated/node-pool: privileged
      containers:
        - name: install-scripts
          image: 799720048698.dkr.ecr.us-east-1.amazonaws.com/install-scripts
          env:
          - name: AWS_REGION
            value: us-east-1
          - name: PROJECT_NAME
            value: "install-scripts"
          - name: USE_EC2_PARAMETERS
            value: "1"
          ports:
            - containerPort: 5000
              $patch: delete
            - name: install-scripts
              containerPort: 80
          resources:
            limits: 
              cpu: 4000m