steps:
  - commands:
      - if [ $IMAGE_TARGET = "" ]; then echo "IMAGE_TARGET required"; exit 1; fi
  - wait

  - commands:
      - make -C images/$IMAGE_TARGET build scan push

  - block: "Release to production"
    if: build.env("IMAGE_TARGET") =~ /^kube-/

  - commands:
      - make -C images/$IMAGE_TARGET push-unversioned
    if: build.env("IMAGE_TARGET") =~ /^kube-/
